# Generated by Django 4.1.7 on 2023-03-09 07:36

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('recent_sum', djongo.models.fields.JSONField(default=dict)),
            ],
        ),
    ]
